version: '3.2'
services:
  nginx:
    # 镜像`nginx:1.22`
    image: nginx:1.22
    # 容器名为'nginx_80'
    container_name: nginx_80
    # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
    restart: unless-stopped
    # 数据卷挂载路径设置,将本机目录映射到容器目录
    volumes:
      - "./conf/nginx.conf:/etc/nginx/nginx.conf"
      - "./conf/default.conf:/etc/nginx/conf.d/default.conf"
      - "./dist:/usr/share/nginx/html"
      - "./docker-temp/log:/var/log/nginx"
    # 设置环境变量,相当于docker run命令中的-e
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    # 映射端口
    ports:
      - "8080:80"
