version: '3.2'
services:
  mysql:
    # 原镜像`mysql:5.7`
    image: mysql:5.7.40-debian
    # 容器名为'mysql-57_3306'
    container_name: mysql-57_3306
    # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
    # restart: unless-stopped
    # 数据卷挂载路径设置,将本机目录映射到容器目录
    volumes:
      - "./docker-temp/mysql5.7/data:/var/lib/mysql"
      - "./docker-temp/mysql5.7/log/mysql:/var/log/mysql"
      - "./my.cnf:/etc/mysql/my.cnf"
      # 可执行初始化sql脚本的目录 -- tips:`/var/lib/mysql`目录下无数据的时候才会执行(即第一次启动的时候才会执行)
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    # 设置环境变量,相当于docker run命令中的-e
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      # 设置root用户密码
      MYSQL_ROOT_PASSWORD: root
      # 初始化的数据库名称
      MYSQL_DATABASE: demo
      # 映射端口
    ports:
      - "3306:3306"
